import { AdminActivityItem, Booking, Driver, Payment } from "@/types/admin";

export const initialDrivers: Driver[] = [
  {
    id: "DRV-001",
    name: "Ousman Jallow",
    phone: "+220 775 1101",
    vehicleName: "Toyota Vitz",
    vehiclePlate: "BJL 4321 A",
    availabilityStatus: "available",
    tripsToday: 4,
    reportedEarnings: 980,
  },
  {
    id: "DRV-002",
    name: "Fatou Camara",
    phone: "+220 776 2202",
    vehicleName: "Nissan Sunny",
    vehiclePlate: "KM 1098 B",
    availabilityStatus: "assigned",
    activeBookingId: "BK-2401",
    tripsToday: 3,
    reportedEarnings: 760,
  },
  {
    id: "DRV-003",
    name: "Lamin Ceesay",
    phone: "+220 777 3303",
    vehicleName: "Hyundai Accent",
    vehiclePlate: "BS 5643 C",
    availabilityStatus: "on-trip",
    activeBookingId: "BK-2403",
    tripsToday: 5,
    reportedEarnings: 1180,
  },
  {
    id: "DRV-004",
    name: "Awa Sowe",
    phone: "+220 778 4404",
    vehicleName: "Toyota Corolla",
    vehiclePlate: "SK 7788 D",
    availabilityStatus: "offline",
    tripsToday: 2,
    reportedEarnings: 450,
  },
];

export const initialBookings: Booking[] = [
  {
    id: "BK-2401",
    customerName: "Mariama Jobe",
    customerPhone: "+220 314 7788",
    pickupLocation: "Serrekunda Market",
    dropoffLocation: "Banjul Ferry Terminal",
    pickupTime: "Now",
    estimatedFare: 180,
    paymentMethod: "mobile-money",
    paymentStatus: "pending-mobile-money",
    rideStatus: "assigned",
    assignedDriverId: "DRV-002",
    notes: "Call when nearby",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "BK-2402",
    customerName: "Ibrahima Bah",
    customerPhone: "+220 398 1099",
    pickupLocation: "Kairaba Avenue",
    dropoffLocation: "Kololi Beach",
    pickupTime: "17:30",
    estimatedFare: 140,
    paymentMethod: "cash",
    paymentStatus: "unpaid",
    rideStatus: "new-request",
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "BK-2403",
    customerName: "Sainabou Touray",
    customerPhone: "+220 794 5522",
    pickupLocation: "Brikama Garage",
    dropoffLocation: "Westfield Junction",
    pickupTime: "Now",
    estimatedFare: 230,
    paymentMethod: "mobile-money",
    paymentStatus: "paid",
    rideStatus: "in-progress",
    assignedDriverId: "DRV-003",
    createdAt: new Date(Date.now() - 1000 * 60 * 52).toISOString(),
  },
  {
    id: "BK-2404",
    customerName: "Momodou Sallah",
    customerPhone: "+220 206 9871",
    pickupLocation: "Bakau New Town",
    dropoffLocation: "Banjul Airport",
    pickupTime: "Tomorrow 08:15",
    estimatedFare: 320,
    paymentMethod: "mobile-money",
    paymentStatus: "paid",
    rideStatus: "completed",
    assignedDriverId: "DRV-001",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "BK-2405",
    customerName: "Amie Njie",
    customerPhone: "+220 665 0098",
    pickupLocation: "Latrikunda Sabiji",
    dropoffLocation: "Bertil Harding Highway",
    pickupTime: "Now",
    estimatedFare: 150,
    paymentMethod: "cash",
    paymentStatus: "failed",
    rideStatus: "pending-confirmation",
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];

export const initialPayments: Payment[] = [
  {
    id: "PAY-9001",
    bookingId: "BK-2403",
    customerName: "Sainabou Touray",
    amount: 230,
    method: "mobile-money",
    status: "paid",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "PAY-9002",
    bookingId: "BK-2404",
    customerName: "Momodou Sallah",
    amount: 320,
    method: "mobile-money",
    status: "paid",
    createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
  },
  {
    id: "PAY-9003",
    bookingId: "BK-2401",
    customerName: "Mariama Jobe",
    amount: 180,
    method: "mobile-money",
    status: "pending-mobile-money",
    createdAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
  },
  {
    id: "PAY-9004",
    bookingId: "BK-2405",
    customerName: "Amie Njie",
    amount: 150,
    method: "cash",
    status: "failed",
    createdAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
  },
];

export const initialActivity: AdminActivityItem[] = [
  {
    id: "ACT-01",
    type: "new-booking",
    title: "New booking request",
    message: "BK-2405 from Latrikunda Sabiji to Bertil Harding Highway",
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    bookingId: "BK-2405",
    isNew: true,
  },
  {
    id: "ACT-02",
    type: "payment-updated",
    title: "Payment completed",
    message: "BK-2403 was paid via Mobile Money",
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    bookingId: "BK-2403",
  },
  {
    id: "ACT-03",
    type: "driver-assigned",
    title: "Driver assigned",
    message: "Ousman Jallow assigned to BK-2404",
    createdAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    bookingId: "BK-2404",
  },
];
